# apiVersion: v1
# kind: Service
# metadata:
#   name: app-nodeport-svc
#   labels:
#     app: app-lanchonete
# spec:
#   type: NodePort
#   selector:
#     app: app-lanchonete
#   ports:
#   - port: 80
#     targetPort: 3000
#     nodePort: 30000
#     protocol: TCP

apiVersion: v1
kind: Service
metadata:
  name: app-lanchonete-service
spec:
  type: LoadBalancer
  selector:
    app: app-lanchonete
  ports:
  - protocol: TCP
    port: 30000
    targetPort: 3000